name: Build and publish python package to Test PyPI

on:
  release:
    types: [ published ]

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish PyPi package
        uses: code-specialist/pypi-poetry-publish@v1.1
        with:
          PYTHON_VERSION: "3.10"
          PACKAGE_DIRECTORY: './sqlmodel_repository/'
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          BRANCH: "main"
