name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Poetry Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ matrix.python-version }}

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Test Infrastructure
        run: |
          docker-compose -f tests/docker-compose.yaml up -d
        shell: bash

      - name: Install poetry
        run: pip install poetry
        shell: bash

      - name: Install dependencies
        run: poetry install
        shell: bash

      - name: Run Tests
        run: poetry run pytest
        shell: bash

      - name: Teardown Test Infrastructure
        if: always()
        run: |
          docker-compose -f tests/docker-compose.yaml down
        shell: bash
